<a href="https://colab.research.google.com/github/nikhilkalghatgi/learning/blob/main/PyTorch/torch_tensor_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.1.0+cu118


In [2]:
scalar = torch.tensor(7)

In [3]:
scalar.ndim  # number of square brakets
scalar.item()  # getting the actual values with actual data types and not as a tensor
scalar.shape   # dimensios of elements

torch.Size([])

In [4]:
t = torch.tensor([[
    [1,2],
    [2,3],
    [6,4]]]
)
t.ndim      # number of nested brackets -> this will be = number of dimesions ie: in tensor of shape [16, 32, 8, 8], the ndim = 4 since 4 elements
t.shape

torch.Size([1, 3, 2])

In [5]:
random_tensor = torch.rand(3,5)
random_tensor

tensor([[0.1420, 0.4608, 0.0507, 0.1437, 0.8013],
        [0.2289, 0.6959, 0.8992, 0.0851, 0.3949],
        [0.7504, 0.8474, 0.3135, 0.3179, 0.0024]])

In [6]:
# random tensor for image
rim = torch.rand(size=(32,32,3)) # height, width, color
rim.shape

torch.Size([32, 32, 3])

In [7]:
zeros = torch.zeros(size=(3,4))
ones = torch.ones(size=(3,4))
ones.dtype        # check data type of tensor

torch.float32

### RANGE AND TENSOR LIKE

In [8]:
on2ten = torch.arange(0,10)       # .range is depricated so .arange is sued
onetotenstep = torch.arange(start=0, end=100, step=7)
onetotenstep

tensor([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

In [9]:
# LIKE
ten_zeros = torch.zeros_like(input=on2ten)          # it will output same shape as input
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## TENSOR OPERATIONS

In [10]:
tensor = torch.tensor([1, 2, 3])
tensor + 10       # adding a scalar
tensor * 10       # miltipling a scalar

tensor([10, 20, 30])

In [11]:
# Torch inbuilt functions
torch.mul(tensor, 10)
torch.add(tensor, 10)

tensor([11, 12, 13])

### MATRIX MULTIPLICATION

In [12]:
tensor

tensor([1, 2, 3])

In [13]:
# Elementwise mult
print(tensor * tensor)  # 1x1 , 2x2, 3x3

# Dot product ir matrix mult
torch.matmul(tensor, tensor)  # = 1x1 + 2x2 + 3x3

# OR
tensor @ tensor    # @ is used for matrix mult

tensor([1, 4, 9])


tensor(14)

In [14]:
#
tensorA = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]
])

tensorB = torch.tensor([
    [7, 10],
    [8, 11],
    [9, 12]
])

# TRANSPOSE
tensorB = tensorB.T

# TORCH.MM IS SAME AS TORCH.MATMUL
torch.mm(tensorA, tensorB)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### MIN MAX AND SUM

In [15]:
x = torch.arange(0, 100, 10)    # x is of type int64, which is long

torch.min(x), x.min()    # Both are same
torch.max(x) , x.max()
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [16]:
#torch.mean(x) # this will throw error cuz x is int64 (long) but mean() expects float
torch.mean(x.type(torch.float32))
x.type(torch.float32).mean()

tensor(45.)

### FIND POSITIONAL MIN AND MAX

In [17]:
# Find the position in tensor X that has min value -> returns index pos of X with min value
x.argmin()

# similarly
x.argmax()

tensor(9)

### RESHAPING , VIEWING , STACKING, SQUEEZING AND UNSQUEEZING

In [18]:
import torch
x = torch.arange(1., 10.)
x.dtype

torch.float32

In [19]:
# RESHAPE
x_reshaped = x.reshape(1, 9)   # Just adds 1 dimension extra
print(x_reshaped.shape)

#x_reshaped = x.reshape(2, 9)   # error: cuz 2*9 = 18 and 9 cannot be split into 18 parts
print(x_reshaped.shape)

x_reshaped = x.reshape(9, 1)   # creates 9 rows and one col
print(x_reshaped.shape)

# eg 2:
x1 = torch.arange(1., 11.) # 10 elements
x_reshaped1 = x1.reshape(5,2)   # 5*2 = 10 so it will work
print(x_reshaped1.shape)

torch.Size([1, 9])
torch.Size([1, 9])
torch.Size([9, 1])
torch.Size([5, 2])


In [20]:
# VIEW
z = x.view(1, 9)
print(z, z.shape)

# NOTE:
# CHANGEING Z CHANGES X CUZ VIEW OF A TENSOR SHARES THE SAME MEMORY AS THE ORIGINAL
z[:, 0] = 5
z,x

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])


(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [21]:
# STACK
x_stacked1 = torch.stack([x,x,x,x], dim=0)
x_stacked2 = torch.stack([x,x,x,x], dim=1)  # dim is the dimension of the new tensor
x, x_stacked1, x_stacked2

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]))

In [22]:
# SQUEEZE
x = torch.zeros(2,1,2,1,2)
x.shape

torch.Size([2, 1, 2, 1, 2])

In [23]:
y = torch.squeeze(x)
x.shape, t.shape, x, y


(torch.Size([2, 1, 2, 1, 2]),
 torch.Size([1, 3, 2]),
 tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]))

In [24]:
x = torch.arange(0,100,10, dtype=torch.float32)
x.unsqueeze(dim=-1), x.unsqueeze(dim=0)

(tensor([[ 0.],
         [10.],
         [20.],
         [30.],
         [40.],
         [50.],
         [60.],
         [70.],
         [80.],
         [90.]]),
 tensor([[ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.]]))

In [25]:
x = torch.arange(1,10)
x = x.reshape(1,3,3)

In [26]:
x[:, 0]     # : only applies to 1st dim

tensor([[1, 2, 3]])

In [27]:
x[:,:,0]   # : applies to 1st 2 dims

tensor([[1, 4, 7]])

## NUMPY TENSOR

In [28]:
import torch
import numpy as np

arr = np.arange(1.,8.)    # numpy default float type is float 63
x = torch.from_numpy(arr) # torch's default float type is float 32 but since its now imported from arr, its now float 64
x

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

In [29]:
# tensor to numpy
tensor = torch.ones(7)
np_tensor = tensor.numpy()  # dype of np_tensor will be float 32 as its derived from tensor whose default dtype is float 32
tensor, np_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## RANDOM SEED

In [30]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
rand_A = torch.rand(2,2)

torch.manual_seed(RANDOM_SEED)    # NOTE: above every rand fn we need to add that line manual_seed, cuz thats how it works
rand_B = torch.rand(2,2)

rand_A, rand_B

(tensor([[0.8823, 0.9150],
         [0.3829, 0.9593]]),
 tensor([[0.8823, 0.9150],
         [0.3829, 0.9593]]))

## GPU

In [31]:
import torch
torch.cuda.is_available()

True

In [32]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [33]:
# count number of devices
torch.cuda.device_count()

1

In [34]:
# TENSORS AND MODELS ON GPU
tensor = torch.tensor([1, 2, 3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [36]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [41]:
# Moving tensors back to cpu
tensor_to_cpu = tensor_on_gpu.cpu().detach().numpy()
tensor_to_cpu

array([1, 2, 3])